//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignPrac1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daily_Log()
        {
            this.Daily_Exercise = new HashSet<Daily_Exercise>();
            this.Daily_Measurement = new HashSet<Daily_Measurement>();
            this.Daily_Meal = new HashSet<Daily_Meal>();
        }
    
        public int Log_Id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<int> Activity_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Progress { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Exercise> Daily_Exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Measurement> Daily_Measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Meal> Daily_Meal { get; set; }
    }
}
