//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignPrac1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalWeightTrackerEntities3 : DbContext
    {
        public AnimalWeightTrackerEntities3()
            : base("name=AnimalWeightTrackerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Daily_Exercise> Daily_Exercise { get; set; }
        public virtual DbSet<Daily_Log> Daily_Log { get; set; }
        public virtual DbSet<Daily_Meal> Daily_Meal { get; set; }
        public virtual DbSet<Daily_Measurement> Daily_Measurement { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
